name: bitcoin_message_signer
version: 1.0.2
description: Sign messages like bitcoin core https://github.com/bitcoin/bitcoin

repository: https://github.com/Satoshi-Engineering/dart-bitcoin-message-signer

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pointycastle: ^3.7.4
  blockchain_utils: ^2.1.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
